version: '3.8'
services:
  sqlsrv:
    container_name: sqlsrv
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPassword123.
    restart: unless-stopped
    networks:
      - webnet
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql/sql-data.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 15 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyPassword123. -i /init.sql;
      wait
      "
volumes:
  sql_data:
    driver: local
networks:
  webnet:
    driver: bridge